### ISSUE TITLE
Not clear what plan to choose

### ISSUE THREAD

**Issue by varnav** [ellisvalentiner/dte-rate-comparison#8]
App recommends:

Residential Time of Day (D1.11) 

Plans I see on DTE site are:

Time Of Day 3 p.m. - 7 p.m.
Time Of Day 11 a.m. - 7 p.m.

**Comment by ellisvalentiner** [comment]
@varnav Hi, you can find an overview of DTE's residential electric rates [here](https://www.dteenergy.com/content/dam/dteenergy/deg/website/residential/Service-Request/pricing/residential-pricing-options/Residential-Electric-Pricing-Options.pdf) (PDF)

The 3 main rate options are:

- Time of Day 3 p.m. – 7 p.m. Standard Base Rate  (D1.11)
- Time of Day 11 a.m. - 7 p.m. Rate (D1.2)
- Dynamic Peak Pricing Rate (D1.8)

Their current electric rate book with **all** rates is [here](https://www.michigan.gov/-/media/Project/Websites/mpsc/consumer/rate-books/electric/dte/dtee1cur.pdf?rev=e0168ab41b8245bba5f3ca7631c29614)

I'd recommend using [DTE's simulator](https://www.dteenergy.com/us/en/residential/service-request/pricing/rate-options/residential-pricing-options.html) since my app is not well maintained and may not be up to date with the latest rate prices.
